language: go

go:
  - 1.13.x

before_install:
  - ./build/install-protobuf.sh
  - export PATH=$PATH:$GOPATH/bin
  - go mod download
  - go get github.com/golang/protobuf/protoc-gen-go
install: true

script:
  - env GO111MODULE=on make all
