// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node_config_events.proto

package nodeconfig

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SFTPAuth_SFTPAuthType int32

const (
	SFTPAuth_SFTP_AUTH_TYPE_UNSPECIFIED SFTPAuth_SFTPAuthType = 0
	SFTPAuth_PASSWORD                   SFTPAuth_SFTPAuthType = 1
	SFTPAuth_KEYBASED                   SFTPAuth_SFTPAuthType = 2
	SFTPAuth_KEYPASSPHRASE              SFTPAuth_SFTPAuthType = 3
)

var SFTPAuth_SFTPAuthType_name = map[int32]string{
	0: "SFTP_AUTH_TYPE_UNSPECIFIED",
	1: "PASSWORD",
	2: "KEYBASED",
	3: "KEYPASSPHRASE",
}

var SFTPAuth_SFTPAuthType_value = map[string]int32{
	"SFTP_AUTH_TYPE_UNSPECIFIED": 0,
	"PASSWORD":                   1,
	"KEYBASED":                   2,
	"KEYPASSPHRASE":              3,
}

func (x SFTPAuth_SFTPAuthType) String() string {
	return proto.EnumName(SFTPAuth_SFTPAuthType_name, int32(x))
}

func (SFTPAuth_SFTPAuthType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_98a96787b4b9490b, []int{1, 0}
}

type NodeConfig_NodeType int32

const (
	NodeConfig_NODETYPE_UNSPECIFIED NodeConfig_NodeType = 0
	NodeConfig_NODETYPE_MASTER      NodeConfig_NodeType = 1
	NodeConfig_NODETYPE_NODE        NodeConfig_NodeType = 2
	NodeConfig_NODETYPE_EXTERNAL    NodeConfig_NodeType = 3
)

var NodeConfig_NodeType_name = map[int32]string{
	0: "NODETYPE_UNSPECIFIED",
	1: "NODETYPE_MASTER",
	2: "NODETYPE_NODE",
	3: "NODETYPE_EXTERNAL",
}

var NodeConfig_NodeType_value = map[string]int32{
	"NODETYPE_UNSPECIFIED": 0,
	"NODETYPE_MASTER":      1,
	"NODETYPE_NODE":        2,
	"NODETYPE_EXTERNAL":    3,
}

func (x NodeConfig_NodeType) String() string {
	return proto.EnumName(NodeConfig_NodeType_name, int32(x))
}

func (NodeConfig_NodeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_98a96787b4b9490b, []int{2, 0}
}

type NodeConfig_SZ int32

const (
	NodeConfig_SZ_UNSPECIFIED  NodeConfig_SZ = 0
	NodeConfig_SZ_EXTERNAL     NodeConfig_SZ = 10
	NodeConfig_SZ_DMZ          NodeConfig_SZ = 20
	NodeConfig_SZ_APP          NodeConfig_SZ = 30
	NodeConfig_SZ_DATA         NodeConfig_SZ = 40
	NodeConfig_SZ_CONTROLPLANE NodeConfig_SZ = 50
)

var NodeConfig_SZ_name = map[int32]string{
	0:  "SZ_UNSPECIFIED",
	10: "SZ_EXTERNAL",
	20: "SZ_DMZ",
	30: "SZ_APP",
	40: "SZ_DATA",
	50: "SZ_CONTROLPLANE",
}

var NodeConfig_SZ_value = map[string]int32{
	"SZ_UNSPECIFIED":  0,
	"SZ_EXTERNAL":     10,
	"SZ_DMZ":          20,
	"SZ_APP":          30,
	"SZ_DATA":         40,
	"SZ_CONTROLPLANE": 50,
}

func (x NodeConfig_SZ) String() string {
	return proto.EnumName(NodeConfig_SZ_name, int32(x))
}

func (NodeConfig_SZ) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_98a96787b4b9490b, []int{2, 1}
}

type AddNodeConfigResponse_NodeEntryStatus int32

const (
	AddNodeConfigResponse_NODE_ENTRY_STATUS_UNSPECIFIED AddNodeConfigResponse_NodeEntryStatus = 0
	AddNodeConfigResponse_NODE_ENTRY_STATUS_SUCCESS     AddNodeConfigResponse_NodeEntryStatus = 1
	AddNodeConfigResponse_NODE_ENTRY_STATUS_ERROR       AddNodeConfigResponse_NodeEntryStatus = 2
)

var AddNodeConfigResponse_NodeEntryStatus_name = map[int32]string{
	0: "NODE_ENTRY_STATUS_UNSPECIFIED",
	1: "NODE_ENTRY_STATUS_SUCCESS",
	2: "NODE_ENTRY_STATUS_ERROR",
}

var AddNodeConfigResponse_NodeEntryStatus_value = map[string]int32{
	"NODE_ENTRY_STATUS_UNSPECIFIED": 0,
	"NODE_ENTRY_STATUS_SUCCESS":     1,
	"NODE_ENTRY_STATUS_ERROR":       2,
}

func (x AddNodeConfigResponse_NodeEntryStatus) String() string {
	return proto.EnumName(AddNodeConfigResponse_NodeEntryStatus_name, int32(x))
}

func (AddNodeConfigResponse_NodeEntryStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_98a96787b4b9490b, []int{3, 0}
}

// node config events
type GRPCAuth struct {
	TlsCert              string   `protobuf:"bytes,1,opt,name=tls_cert,json=tlsCert,proto3" json:"tls_cert,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GRPCAuth) Reset()         { *m = GRPCAuth{} }
func (m *GRPCAuth) String() string { return proto.CompactTextString(m) }
func (*GRPCAuth) ProtoMessage()    {}
func (*GRPCAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_98a96787b4b9490b, []int{0}
}

func (m *GRPCAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GRPCAuth.Unmarshal(m, b)
}
func (m *GRPCAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GRPCAuth.Marshal(b, m, deterministic)
}
func (m *GRPCAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GRPCAuth.Merge(m, src)
}
func (m *GRPCAuth) XXX_Size() int {
	return xxx_messageInfo_GRPCAuth.Size(m)
}
func (m *GRPCAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_GRPCAuth.DiscardUnknown(m)
}

var xxx_messageInfo_GRPCAuth proto.InternalMessageInfo

func (m *GRPCAuth) GetTlsCert() string {
	if m != nil {
		return m.TlsCert
	}
	return ""
}

type SFTPAuth struct {
	SftpAuthType         SFTPAuth_SFTPAuthType `protobuf:"varint,1,opt,name=sftp_auth_type,json=sftpAuthType,proto3,enum=nodeconfig.SFTPAuth_SFTPAuthType" json:"sftp_auth_type,omitempty"`
	Username             string                `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string                `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Key                  string                `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SFTPAuth) Reset()         { *m = SFTPAuth{} }
func (m *SFTPAuth) String() string { return proto.CompactTextString(m) }
func (*SFTPAuth) ProtoMessage()    {}
func (*SFTPAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_98a96787b4b9490b, []int{1}
}

func (m *SFTPAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SFTPAuth.Unmarshal(m, b)
}
func (m *SFTPAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SFTPAuth.Marshal(b, m, deterministic)
}
func (m *SFTPAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SFTPAuth.Merge(m, src)
}
func (m *SFTPAuth) XXX_Size() int {
	return xxx_messageInfo_SFTPAuth.Size(m)
}
func (m *SFTPAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_SFTPAuth.DiscardUnknown(m)
}

var xxx_messageInfo_SFTPAuth proto.InternalMessageInfo

func (m *SFTPAuth) GetSftpAuthType() SFTPAuth_SFTPAuthType {
	if m != nil {
		return m.SftpAuthType
	}
	return SFTPAuth_SFTP_AUTH_TYPE_UNSPECIFIED
}

func (m *SFTPAuth) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SFTPAuth) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SFTPAuth) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type NodeConfig struct {
	NodeId               string              `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Nodetype             NodeConfig_NodeType `protobuf:"varint,2,opt,name=nodetype,proto3,enum=nodeconfig.NodeConfig_NodeType" json:"nodetype,omitempty"`
	GrpcAddress          string              `protobuf:"bytes,3,opt,name=grpc_address,json=grpcAddress,proto3" json:"grpc_address,omitempty"`
	SftpAddress          string              `protobuf:"bytes,4,opt,name=sftp_address,json=sftpAddress,proto3" json:"sftp_address,omitempty"`
	Sz                   NodeConfig_SZ       `protobuf:"varint,6,opt,name=sz,proto3,enum=nodeconfig.NodeConfig_SZ" json:"sz,omitempty"`
	GrpcAuth             *GRPCAuth           `protobuf:"bytes,7,opt,name=grpc_auth,json=grpcAuth,proto3" json:"grpc_auth,omitempty"`
	SftpAuth             *SFTPAuth           `protobuf:"bytes,8,opt,name=sftp_auth,json=sftpAuth,proto3" json:"sftp_auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *NodeConfig) Reset()         { *m = NodeConfig{} }
func (m *NodeConfig) String() string { return proto.CompactTextString(m) }
func (*NodeConfig) ProtoMessage()    {}
func (*NodeConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_98a96787b4b9490b, []int{2}
}

func (m *NodeConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeConfig.Unmarshal(m, b)
}
func (m *NodeConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeConfig.Marshal(b, m, deterministic)
}
func (m *NodeConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeConfig.Merge(m, src)
}
func (m *NodeConfig) XXX_Size() int {
	return xxx_messageInfo_NodeConfig.Size(m)
}
func (m *NodeConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeConfig.DiscardUnknown(m)
}

var xxx_messageInfo_NodeConfig proto.InternalMessageInfo

func (m *NodeConfig) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *NodeConfig) GetNodetype() NodeConfig_NodeType {
	if m != nil {
		return m.Nodetype
	}
	return NodeConfig_NODETYPE_UNSPECIFIED
}

func (m *NodeConfig) GetGrpcAddress() string {
	if m != nil {
		return m.GrpcAddress
	}
	return ""
}

func (m *NodeConfig) GetSftpAddress() string {
	if m != nil {
		return m.SftpAddress
	}
	return ""
}

func (m *NodeConfig) GetSz() NodeConfig_SZ {
	if m != nil {
		return m.Sz
	}
	return NodeConfig_SZ_UNSPECIFIED
}

func (m *NodeConfig) GetGrpcAuth() *GRPCAuth {
	if m != nil {
		return m.GrpcAuth
	}
	return nil
}

func (m *NodeConfig) GetSftpAuth() *SFTPAuth {
	if m != nil {
		return m.SftpAuth
	}
	return nil
}

type AddNodeConfigResponse struct {
	NodeId               string                                `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeEntryMessage     string                                `protobuf:"bytes,2,opt,name=node_entry_message,json=nodeEntryMessage,proto3" json:"node_entry_message,omitempty"`
	NodeEntryStatus      AddNodeConfigResponse_NodeEntryStatus `protobuf:"varint,3,opt,name=node_entry_status,json=nodeEntryStatus,proto3,enum=nodeconfig.AddNodeConfigResponse_NodeEntryStatus" json:"node_entry_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *AddNodeConfigResponse) Reset()         { *m = AddNodeConfigResponse{} }
func (m *AddNodeConfigResponse) String() string { return proto.CompactTextString(m) }
func (*AddNodeConfigResponse) ProtoMessage()    {}
func (*AddNodeConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98a96787b4b9490b, []int{3}
}

func (m *AddNodeConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNodeConfigResponse.Unmarshal(m, b)
}
func (m *AddNodeConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNodeConfigResponse.Marshal(b, m, deterministic)
}
func (m *AddNodeConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNodeConfigResponse.Merge(m, src)
}
func (m *AddNodeConfigResponse) XXX_Size() int {
	return xxx_messageInfo_AddNodeConfigResponse.Size(m)
}
func (m *AddNodeConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNodeConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddNodeConfigResponse proto.InternalMessageInfo

func (m *AddNodeConfigResponse) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *AddNodeConfigResponse) GetNodeEntryMessage() string {
	if m != nil {
		return m.NodeEntryMessage
	}
	return ""
}

func (m *AddNodeConfigResponse) GetNodeEntryStatus() AddNodeConfigResponse_NodeEntryStatus {
	if m != nil {
		return m.NodeEntryStatus
	}
	return AddNodeConfigResponse_NODE_ENTRY_STATUS_UNSPECIFIED
}

type NodeID struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeID) Reset()         { *m = NodeID{} }
func (m *NodeID) String() string { return proto.CompactTextString(m) }
func (*NodeID) ProtoMessage()    {}
func (*NodeID) Descriptor() ([]byte, []int) {
	return fileDescriptor_98a96787b4b9490b, []int{4}
}

func (m *NodeID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeID.Unmarshal(m, b)
}
func (m *NodeID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeID.Marshal(b, m, deterministic)
}
func (m *NodeID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeID.Merge(m, src)
}
func (m *NodeID) XXX_Size() int {
	return xxx_messageInfo_NodeID.Size(m)
}
func (m *NodeID) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeID.DiscardUnknown(m)
}

var xxx_messageInfo_NodeID proto.InternalMessageInfo

func (m *NodeID) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

type ListNodeConfigRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListNodeConfigRequest) Reset()         { *m = ListNodeConfigRequest{} }
func (m *ListNodeConfigRequest) String() string { return proto.CompactTextString(m) }
func (*ListNodeConfigRequest) ProtoMessage()    {}
func (*ListNodeConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98a96787b4b9490b, []int{5}
}

func (m *ListNodeConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNodeConfigRequest.Unmarshal(m, b)
}
func (m *ListNodeConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNodeConfigRequest.Marshal(b, m, deterministic)
}
func (m *ListNodeConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNodeConfigRequest.Merge(m, src)
}
func (m *ListNodeConfigRequest) XXX_Size() int {
	return xxx_messageInfo_ListNodeConfigRequest.Size(m)
}
func (m *ListNodeConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNodeConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListNodeConfigRequest proto.InternalMessageInfo

type AllNodeConfig struct {
	AllNodeConfig        []*NodeConfig `protobuf:"bytes,1,rep,name=all_node_config,json=allNodeConfig,proto3" json:"all_node_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AllNodeConfig) Reset()         { *m = AllNodeConfig{} }
func (m *AllNodeConfig) String() string { return proto.CompactTextString(m) }
func (*AllNodeConfig) ProtoMessage()    {}
func (*AllNodeConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_98a96787b4b9490b, []int{6}
}

func (m *AllNodeConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllNodeConfig.Unmarshal(m, b)
}
func (m *AllNodeConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllNodeConfig.Marshal(b, m, deterministic)
}
func (m *AllNodeConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllNodeConfig.Merge(m, src)
}
func (m *AllNodeConfig) XXX_Size() int {
	return xxx_messageInfo_AllNodeConfig.Size(m)
}
func (m *AllNodeConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AllNodeConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AllNodeConfig proto.InternalMessageInfo

func (m *AllNodeConfig) GetAllNodeConfig() []*NodeConfig {
	if m != nil {
		return m.AllNodeConfig
	}
	return nil
}

func init() {
	proto.RegisterEnum("nodeconfig.SFTPAuth_SFTPAuthType", SFTPAuth_SFTPAuthType_name, SFTPAuth_SFTPAuthType_value)
	proto.RegisterEnum("nodeconfig.NodeConfig_NodeType", NodeConfig_NodeType_name, NodeConfig_NodeType_value)
	proto.RegisterEnum("nodeconfig.NodeConfig_SZ", NodeConfig_SZ_name, NodeConfig_SZ_value)
	proto.RegisterEnum("nodeconfig.AddNodeConfigResponse_NodeEntryStatus", AddNodeConfigResponse_NodeEntryStatus_name, AddNodeConfigResponse_NodeEntryStatus_value)
	proto.RegisterType((*GRPCAuth)(nil), "nodeconfig.GRPCAuth")
	proto.RegisterType((*SFTPAuth)(nil), "nodeconfig.SFTPAuth")
	proto.RegisterType((*NodeConfig)(nil), "nodeconfig.NodeConfig")
	proto.RegisterType((*AddNodeConfigResponse)(nil), "nodeconfig.AddNodeConfigResponse")
	proto.RegisterType((*NodeID)(nil), "nodeconfig.NodeID")
	proto.RegisterType((*ListNodeConfigRequest)(nil), "nodeconfig.ListNodeConfigRequest")
	proto.RegisterType((*AllNodeConfig)(nil), "nodeconfig.AllNodeConfig")
}

func init() { proto.RegisterFile("node_config_events.proto", fileDescriptor_98a96787b4b9490b) }

var fileDescriptor_98a96787b4b9490b = []byte{
	// 680 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0x5d, 0x6f, 0xda, 0x48,
	0x14, 0x5d, 0x9b, 0x08, 0x9c, 0x0b, 0x01, 0x67, 0x36, 0xd9, 0x38, 0x59, 0x25, 0x1b, 0x2c, 0xad,
	0xc4, 0x4a, 0xab, 0x48, 0xa1, 0x8f, 0x95, 0x2a, 0xb9, 0x30, 0x49, 0x50, 0x08, 0x58, 0x33, 0x46,
	0x2d, 0x48, 0xd1, 0xc8, 0xc5, 0x93, 0x0f, 0x95, 0x80, 0xeb, 0x19, 0x5a, 0x91, 0xd7, 0xfe, 0xa0,
	0xfe, 0xc1, 0x3e, 0x54, 0x33, 0xc6, 0xe0, 0xe6, 0xe3, 0xed, 0xde, 0x73, 0xce, 0x9d, 0x3b, 0x73,
	0xee, 0xb5, 0xc1, 0x99, 0xce, 0x22, 0xce, 0xc6, 0xb3, 0xe9, 0xcd, 0xfd, 0x2d, 0xe3, 0x5f, 0xf9,
	0x54, 0x8a, 0x93, 0x38, 0x99, 0xc9, 0x19, 0x02, 0xc5, 0xa4, 0x84, 0xfb, 0x2f, 0x58, 0xe7, 0xc4,
	0x6f, 0x79, 0x73, 0x79, 0x87, 0xf6, 0xc1, 0x92, 0x13, 0xc1, 0xc6, 0x3c, 0x91, 0x8e, 0x71, 0x6c,
	0x34, 0x36, 0x49, 0x49, 0x4e, 0x44, 0x8b, 0x27, 0xd2, 0xfd, 0x69, 0x80, 0x45, 0xcf, 0x02, 0x5f,
	0xeb, 0xce, 0xa1, 0x2a, 0x6e, 0x64, 0xcc, 0xc2, 0xb9, 0xbc, 0x63, 0x72, 0x11, 0x73, 0xad, 0xae,
	0x36, 0xeb, 0x27, 0xeb, 0x83, 0x4f, 0x32, 0xf5, 0x2a, 0x08, 0x16, 0x31, 0x27, 0x15, 0x55, 0x98,
	0x65, 0xe8, 0x00, 0xac, 0xb9, 0xe0, 0xc9, 0x34, 0x7c, 0xe0, 0x8e, 0xa9, 0x1b, 0xae, 0x72, 0xc5,
	0xc5, 0xa1, 0x10, 0xdf, 0x66, 0x49, 0xe4, 0x14, 0x52, 0x2e, 0xcb, 0x91, 0x0d, 0x85, 0xcf, 0x7c,
	0xe1, 0x6c, 0x68, 0x58, 0x85, 0xee, 0x35, 0x54, 0xf2, 0x7d, 0xd0, 0x11, 0x1c, 0xa8, 0x9c, 0x79,
	0x83, 0xe0, 0x82, 0x05, 0x43, 0x1f, 0xb3, 0x41, 0x8f, 0xfa, 0xb8, 0xd5, 0x39, 0xeb, 0xe0, 0xb6,
	0xfd, 0x07, 0xaa, 0x80, 0xe5, 0x7b, 0x94, 0x7e, 0xe8, 0x93, 0xb6, 0x6d, 0xa8, 0xec, 0x12, 0x0f,
	0xdf, 0x7b, 0x14, 0xb7, 0x6d, 0x13, 0x6d, 0xc3, 0xd6, 0x25, 0x1e, 0x2a, 0xda, 0xbf, 0x20, 0x1e,
	0xc5, 0x76, 0xc1, 0xfd, 0xbe, 0x01, 0xd0, 0x9b, 0x45, 0xbc, 0xa5, 0xdf, 0x86, 0xf6, 0xa0, 0xa4,
	0xcd, 0xbd, 0x8f, 0x96, 0x3e, 0x15, 0x55, 0xda, 0x89, 0xd0, 0x5b, 0xb0, 0x54, 0xa4, 0x3d, 0x31,
	0xb5, 0x27, 0xff, 0xe4, 0x3d, 0x59, 0x1f, 0xa1, 0x43, 0xed, 0xc8, 0xaa, 0x00, 0xd5, 0xa1, 0x72,
	0x9b, 0xc4, 0x63, 0x16, 0x46, 0x51, 0xc2, 0x85, 0x58, 0xbe, 0xba, 0xac, 0x30, 0x2f, 0x85, 0x94,
	0x24, 0x75, 0x7e, 0x29, 0x49, 0x1d, 0x28, 0x6b, 0x53, 0x97, 0x92, 0xff, 0xc0, 0x14, 0x8f, 0x4e,
	0x51, 0x37, 0xdf, 0x7f, 0xa5, 0x39, 0x1d, 0x11, 0x53, 0x3c, 0xa2, 0x53, 0xd8, 0x4c, 0x1b, 0xce,
	0xe5, 0x9d, 0x53, 0x3a, 0x36, 0x1a, 0xe5, 0xe6, 0x4e, 0xbe, 0x22, 0x5b, 0x0c, 0x62, 0xe9, 0x3b,
	0xa8, 0xd1, 0x9f, 0xc2, 0xe6, 0x6a, 0xf4, 0x8e, 0xf5, 0xbc, 0x24, 0x1b, 0x02, 0xb1, 0xb2, 0x41,
	0xbb, 0x63, 0xb0, 0xb2, 0xc7, 0x22, 0x07, 0x76, 0x7a, 0xfd, 0x36, 0x7e, 0x61, 0x20, 0x7f, 0x42,
	0x6d, 0xc5, 0x5c, 0x79, 0x34, 0xc0, 0xc4, 0x36, 0xd4, 0x24, 0x56, 0xa0, 0x0a, 0x6c, 0x13, 0xed,
	0xc2, 0xf6, 0x0a, 0xc2, 0x1f, 0x03, 0x4c, 0x7a, 0x5e, 0xd7, 0x2e, 0xb8, 0x63, 0x30, 0xe9, 0x08,
	0x21, 0xa8, 0xd2, 0xd1, 0x93, 0x83, 0x6b, 0x50, 0xa6, 0xa3, 0xb5, 0x14, 0x10, 0x40, 0x91, 0x8e,
	0x58, 0xfb, 0x6a, 0x64, 0xef, 0x2c, 0x63, 0xcf, 0xf7, 0xed, 0x23, 0x54, 0x86, 0x92, 0xc2, 0xbd,
	0xc0, 0xb3, 0x1b, 0xea, 0x3a, 0x74, 0xc4, 0x5a, 0xfd, 0x5e, 0x40, 0xfa, 0x5d, 0xbf, 0xeb, 0xf5,
	0xb0, 0xdd, 0x74, 0x7f, 0x98, 0xb0, 0xeb, 0x45, 0xd1, 0xda, 0x48, 0xc2, 0x45, 0x3c, 0x9b, 0x0a,
	0xfe, 0xfa, 0x42, 0xfc, 0x0f, 0x48, 0x13, 0x7c, 0x2a, 0x93, 0x05, 0x7b, 0xe0, 0x42, 0x84, 0xb7,
	0xd9, 0xae, 0xdb, 0x8a, 0xc1, 0x8a, 0xb8, 0x4a, 0x71, 0x74, 0x0d, 0xdb, 0x39, 0xb5, 0x90, 0xa1,
	0x9c, 0xa7, 0x6b, 0x50, 0x6d, 0x9e, 0xe6, 0x5d, 0x7e, 0xf1, 0x12, 0x7a, 0xc0, 0xfa, 0x38, 0xaa,
	0x0b, 0x49, 0x6d, 0xfa, 0x3b, 0xe0, 0xc6, 0x50, 0x7b, 0xa2, 0x41, 0x75, 0x38, 0x54, 0x76, 0x32,
	0xdc, 0x0b, 0xc8, 0x90, 0xd1, 0xc0, 0x0b, 0x06, 0xf4, 0x89, 0x81, 0x87, 0xb0, 0xff, 0x5c, 0x42,
	0x07, 0xad, 0x16, 0xa6, 0xd4, 0x36, 0xd0, 0xdf, 0xb0, 0xf7, 0x9c, 0xc6, 0x84, 0xf4, 0x89, 0x6d,
	0xba, 0x75, 0x28, 0xaa, 0x8e, 0x9d, 0xf6, 0xab, 0x0e, 0xb9, 0x7b, 0xb0, 0xdb, 0xbd, 0x17, 0x32,
	0xff, 0x9e, 0x2f, 0x73, 0x2e, 0xa4, 0xdb, 0x87, 0x2d, 0x6f, 0x32, 0xc9, 0x7d, 0x75, 0xef, 0xa0,
	0x16, 0x4e, 0x26, 0x2c, 0xf7, 0x5b, 0x73, 0x8c, 0xe3, 0x42, 0xa3, 0xdc, 0xfc, 0xeb, 0xe5, 0x35,
	0x27, 0x5b, 0x61, 0xbe, 0xfe, 0x53, 0x51, 0xff, 0xfd, 0xde, 0xfc, 0x0a, 0x00, 0x00, 0xff, 0xff,
	0xe0, 0x97, 0x16, 0xae, 0x19, 0x05, 0x00, 0x00,
}
