// Code generated by protoc-gen-go. DO NOT EDIT.
// source: styxevent.proto

package styxevent

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ack struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ack) Reset()         { *m = Ack{} }
func (m *Ack) String() string { return proto.CompactTextString(m) }
func (*Ack) ProtoMessage()    {}
func (*Ack) Descriptor() ([]byte, []int) {
	return fileDescriptor_1257f2c7de005776, []int{0}
}

func (m *Ack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ack.Unmarshal(m, b)
}
func (m *Ack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ack.Marshal(b, m, deterministic)
}
func (m *Ack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ack.Merge(m, src)
}
func (m *Ack) XXX_Size() int {
	return xxx_messageInfo_Ack.Size(m)
}
func (m *Ack) XXX_DiscardUnknown() {
	xxx_messageInfo_Ack.DiscardUnknown(m)
}

var xxx_messageInfo_Ack proto.InternalMessageInfo

func (m *Ack) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SearchFileInfo struct {
	Jid                  string   `protobuf:"bytes,1,opt,name=jid,proto3" json:"jid,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Filename             string   `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	Directory            string   `protobuf:"bytes,4,opt,name=directory,proto3" json:"directory,omitempty"`
	Server               string   `protobuf:"bytes,5,opt,name=server,proto3" json:"server,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchFileInfo) Reset()         { *m = SearchFileInfo{} }
func (m *SearchFileInfo) String() string { return proto.CompactTextString(m) }
func (*SearchFileInfo) ProtoMessage()    {}
func (*SearchFileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1257f2c7de005776, []int{1}
}

func (m *SearchFileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchFileInfo.Unmarshal(m, b)
}
func (m *SearchFileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchFileInfo.Marshal(b, m, deterministic)
}
func (m *SearchFileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchFileInfo.Merge(m, src)
}
func (m *SearchFileInfo) XXX_Size() int {
	return xxx_messageInfo_SearchFileInfo.Size(m)
}
func (m *SearchFileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchFileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SearchFileInfo proto.InternalMessageInfo

func (m *SearchFileInfo) GetJid() string {
	if m != nil {
		return m.Jid
	}
	return ""
}

func (m *SearchFileInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SearchFileInfo) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *SearchFileInfo) GetDirectory() string {
	if m != nil {
		return m.Directory
	}
	return ""
}

func (m *SearchFileInfo) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

type FoundFile struct {
	Jid                  string   `protobuf:"bytes,1,opt,name=jid,proto3" json:"jid,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Match                string   `protobuf:"bytes,3,opt,name=match,proto3" json:"match,omitempty"`
	Regmatch             string   `protobuf:"bytes,4,opt,name=regmatch,proto3" json:"regmatch,omitempty"`
	Error                string   `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FoundFile) Reset()         { *m = FoundFile{} }
func (m *FoundFile) String() string { return proto.CompactTextString(m) }
func (*FoundFile) ProtoMessage()    {}
func (*FoundFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_1257f2c7de005776, []int{2}
}

func (m *FoundFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FoundFile.Unmarshal(m, b)
}
func (m *FoundFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FoundFile.Marshal(b, m, deterministic)
}
func (m *FoundFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FoundFile.Merge(m, src)
}
func (m *FoundFile) XXX_Size() int {
	return xxx_messageInfo_FoundFile.Size(m)
}
func (m *FoundFile) XXX_DiscardUnknown() {
	xxx_messageInfo_FoundFile.DiscardUnknown(m)
}

var xxx_messageInfo_FoundFile proto.InternalMessageInfo

func (m *FoundFile) GetJid() string {
	if m != nil {
		return m.Jid
	}
	return ""
}

func (m *FoundFile) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *FoundFile) GetMatch() string {
	if m != nil {
		return m.Match
	}
	return ""
}

func (m *FoundFile) GetRegmatch() string {
	if m != nil {
		return m.Regmatch
	}
	return ""
}

func (m *FoundFile) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetRemoteFile struct {
	Jid                  string   `protobuf:"bytes,1,opt,name=jid,proto3" json:"jid,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Sourcefile           string   `protobuf:"bytes,3,opt,name=sourcefile,proto3" json:"sourcefile,omitempty"`
	Destinationfile      string   `protobuf:"bytes,4,opt,name=destinationfile,proto3" json:"destinationfile,omitempty"`
	Sourceserver         string   `protobuf:"bytes,5,opt,name=sourceserver,proto3" json:"sourceserver,omitempty"`
	Authmethod           string   `protobuf:"bytes,6,opt,name=authmethod,proto3" json:"authmethod,omitempty"`
	Username             string   `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	Key                  string   `protobuf:"bytes,9,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRemoteFile) Reset()         { *m = GetRemoteFile{} }
func (m *GetRemoteFile) String() string { return proto.CompactTextString(m) }
func (*GetRemoteFile) ProtoMessage()    {}
func (*GetRemoteFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_1257f2c7de005776, []int{3}
}

func (m *GetRemoteFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRemoteFile.Unmarshal(m, b)
}
func (m *GetRemoteFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRemoteFile.Marshal(b, m, deterministic)
}
func (m *GetRemoteFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRemoteFile.Merge(m, src)
}
func (m *GetRemoteFile) XXX_Size() int {
	return xxx_messageInfo_GetRemoteFile.Size(m)
}
func (m *GetRemoteFile) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRemoteFile.DiscardUnknown(m)
}

var xxx_messageInfo_GetRemoteFile proto.InternalMessageInfo

func (m *GetRemoteFile) GetJid() string {
	if m != nil {
		return m.Jid
	}
	return ""
}

func (m *GetRemoteFile) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GetRemoteFile) GetSourcefile() string {
	if m != nil {
		return m.Sourcefile
	}
	return ""
}

func (m *GetRemoteFile) GetDestinationfile() string {
	if m != nil {
		return m.Destinationfile
	}
	return ""
}

func (m *GetRemoteFile) GetSourceserver() string {
	if m != nil {
		return m.Sourceserver
	}
	return ""
}

func (m *GetRemoteFile) GetAuthmethod() string {
	if m != nil {
		return m.Authmethod
	}
	return ""
}

func (m *GetRemoteFile) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetRemoteFile) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *GetRemoteFile) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type RequestFileTransfer struct {
	Jid                  string   `protobuf:"bytes,1,opt,name=jid,proto3" json:"jid,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Sourcefile           string   `protobuf:"bytes,3,opt,name=sourcefile,proto3" json:"sourcefile,omitempty"`
	Destinationfile      string   `protobuf:"bytes,4,opt,name=destinationfile,proto3" json:"destinationfile,omitempty"`
	Sourceserver         string   `protobuf:"bytes,5,opt,name=sourceserver,proto3" json:"sourceserver,omitempty"`
	Destinationserver    string   `protobuf:"bytes,6,opt,name=destinationserver,proto3" json:"destinationserver,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestFileTransfer) Reset()         { *m = RequestFileTransfer{} }
func (m *RequestFileTransfer) String() string { return proto.CompactTextString(m) }
func (*RequestFileTransfer) ProtoMessage()    {}
func (*RequestFileTransfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_1257f2c7de005776, []int{4}
}

func (m *RequestFileTransfer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestFileTransfer.Unmarshal(m, b)
}
func (m *RequestFileTransfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestFileTransfer.Marshal(b, m, deterministic)
}
func (m *RequestFileTransfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestFileTransfer.Merge(m, src)
}
func (m *RequestFileTransfer) XXX_Size() int {
	return xxx_messageInfo_RequestFileTransfer.Size(m)
}
func (m *RequestFileTransfer) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestFileTransfer.DiscardUnknown(m)
}

var xxx_messageInfo_RequestFileTransfer proto.InternalMessageInfo

func (m *RequestFileTransfer) GetJid() string {
	if m != nil {
		return m.Jid
	}
	return ""
}

func (m *RequestFileTransfer) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *RequestFileTransfer) GetSourcefile() string {
	if m != nil {
		return m.Sourcefile
	}
	return ""
}

func (m *RequestFileTransfer) GetDestinationfile() string {
	if m != nil {
		return m.Destinationfile
	}
	return ""
}

func (m *RequestFileTransfer) GetSourceserver() string {
	if m != nil {
		return m.Sourceserver
	}
	return ""
}

func (m *RequestFileTransfer) GetDestinationserver() string {
	if m != nil {
		return m.Destinationserver
	}
	return ""
}

func init() {
	proto.RegisterType((*Ack)(nil), "styxevent.Ack")
	proto.RegisterType((*SearchFileInfo)(nil), "styxevent.SearchFileInfo")
	proto.RegisterType((*FoundFile)(nil), "styxevent.FoundFile")
	proto.RegisterType((*GetRemoteFile)(nil), "styxevent.GetRemoteFile")
	proto.RegisterType((*RequestFileTransfer)(nil), "styxevent.RequestFileTransfer")
}

func init() { proto.RegisterFile("styxevent.proto", fileDescriptor_1257f2c7de005776) }

var fileDescriptor_1257f2c7de005776 = []byte{
	// 456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0x93, 0x34, 0x8d, 0x47, 0xd0, 0x94, 0xa5, 0x42, 0x4b, 0x84, 0x0a, 0xf2, 0x29, 0x48,
	0x28, 0x42, 0xc0, 0x95, 0x43, 0x7b, 0x68, 0xc5, 0xad, 0x72, 0xf8, 0x81, 0xc5, 0x9e, 0xc4, 0x26,
	0xb6, 0xd7, 0x9d, 0x5d, 0x97, 0xf8, 0x0b, 0xe0, 0xc2, 0xf7, 0xf1, 0x3b, 0x68, 0x77, 0xed, 0xd8,
	0x2e, 0x1c, 0xe8, 0x8d, 0x9b, 0xdf, 0x7b, 0x33, 0x9e, 0x37, 0xb3, 0x3b, 0x0b, 0x73, 0xa5, 0xeb,
	0x3d, 0xde, 0x61, 0xa1, 0x57, 0x25, 0x49, 0x2d, 0x99, 0x7f, 0x20, 0x82, 0x97, 0x30, 0xbe, 0x88,
	0x76, 0x8c, 0xc3, 0x71, 0x8e, 0x4a, 0x89, 0x2d, 0x72, 0xef, 0x95, 0xb7, 0xf4, 0xc3, 0x16, 0x06,
	0x3f, 0x3c, 0x38, 0x59, 0xa3, 0xa0, 0x28, 0xb9, 0x4a, 0x33, 0xfc, 0x54, 0x6c, 0x24, 0x3b, 0x85,
	0xf1, 0xd7, 0x34, 0x6e, 0x02, 0xcd, 0x27, 0x63, 0x30, 0xd1, 0x75, 0x89, 0x7c, 0x64, 0x29, 0xfb,
	0xcd, 0x16, 0x30, 0xdb, 0xa4, 0x19, 0x16, 0x22, 0x47, 0x3e, 0xb6, 0xfc, 0x01, 0xb3, 0x17, 0xe0,
	0xc7, 0x29, 0x61, 0xa4, 0x25, 0xd5, 0x7c, 0x62, 0xc5, 0x8e, 0x60, 0xcf, 0x60, 0xaa, 0x90, 0xee,
	0x90, 0xf8, 0x91, 0x95, 0x1a, 0x14, 0xd4, 0xe0, 0x5f, 0xc9, 0xaa, 0x88, 0x8d, 0x91, 0x7f, 0x34,
	0x71, 0x06, 0x47, 0xb9, 0xd0, 0x51, 0xd2, 0x38, 0x70, 0xc0, 0x58, 0x23, 0xdc, 0x3a, 0xc1, 0x55,
	0x3f, 0x60, 0x93, 0x81, 0x44, 0xb2, 0xad, 0xed, 0x40, 0xf0, 0x73, 0x04, 0x8f, 0xaf, 0x51, 0x87,
	0x98, 0x4b, 0x8d, 0x0f, 0xa8, 0x7f, 0x0e, 0xa0, 0x64, 0x45, 0x11, 0x9a, 0xd6, 0x1b, 0x13, 0x3d,
	0x86, 0x2d, 0x61, 0x1e, 0xa3, 0xd2, 0x69, 0x21, 0x74, 0x2a, 0x0b, 0x1b, 0xe4, 0x0c, 0xdd, 0xa7,
	0x59, 0x00, 0x8f, 0x5c, 0xde, 0x60, 0x34, 0x03, 0xce, 0x54, 0x13, 0x95, 0x4e, 0x72, 0xd4, 0x89,
	0x8c, 0xf9, 0xd4, 0x55, 0xeb, 0x18, 0xd3, 0x77, 0xa5, 0x90, 0xec, 0x91, 0x1c, 0xbb, 0xbe, 0x5b,
	0x6c, 0xb4, 0x52, 0x28, 0xf5, 0x4d, 0x52, 0xcc, 0x67, 0x4e, 0x6b, 0xb1, 0xe9, 0x75, 0x87, 0x35,
	0xf7, 0x5d, 0xaf, 0x3b, 0xac, 0x83, 0x5f, 0x1e, 0x3c, 0x0d, 0xf1, 0xb6, 0x42, 0xa5, 0xcd, 0x34,
	0x3e, 0x93, 0x28, 0xd4, 0x06, 0xe9, 0xbf, 0x9c, 0xca, 0x1b, 0x78, 0xd2, 0x4b, 0x6b, 0x02, 0xdd,
	0x70, 0xfe, 0x14, 0xde, 0x7d, 0x1f, 0xc1, 0x64, 0xad, 0xeb, 0x3d, 0xfb, 0x08, 0x60, 0x5a, 0x73,
	0x77, 0x9f, 0x3d, 0x5f, 0x75, 0x4b, 0x34, 0x5c, 0x87, 0xc5, 0x59, 0x4f, 0xea, 0xee, 0xe7, 0x35,
	0x9c, 0x76, 0xe9, 0x6b, 0x4d, 0x28, 0xf2, 0x07, 0xff, 0x64, 0xe9, 0xbd, 0xf5, 0xd8, 0x05, 0xcc,
	0x43, 0xbc, 0x1d, 0x4c, 0xf9, 0xbc, 0x17, 0xfc, 0x97, 0x53, 0x58, 0x9c, 0xf4, 0x74, 0xb3, 0xdd,
	0x1f, 0x60, 0x76, 0x53, 0x65, 0x99, 0xf5, 0xc5, 0x7b, 0xda, 0xe0, 0x46, 0xdf, 0xcf, 0xba, 0x7c,
	0x0d, 0x8b, 0x54, 0xae, 0xb6, 0x54, 0x46, 0x2b, 0xdc, 0x8b, 0xbc, 0xcc, 0x50, 0x75, 0x11, 0x97,
	0xdd, 0x1b, 0x72, 0xe3, 0x7d, 0x99, 0xda, 0x77, 0xe5, 0xfd, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x52, 0x30, 0x23, 0x4b, 0x6a, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StyxClient is the client API for Styx service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StyxClient interface {
	FileSearch(ctx context.Context, in *SearchFileInfo, opts ...grpc.CallOption) (*FoundFile, error)
	FileSearchStream(ctx context.Context, opts ...grpc.CallOption) (Styx_FileSearchStreamClient, error)
	ReqFileTransfer(ctx context.Context, in *RequestFileTransfer, opts ...grpc.CallOption) (*Ack, error)
	PullFile(ctx context.Context, in *GetRemoteFile, opts ...grpc.CallOption) (*Ack, error)
}

type styxClient struct {
	cc *grpc.ClientConn
}

func NewStyxClient(cc *grpc.ClientConn) StyxClient {
	return &styxClient{cc}
}

func (c *styxClient) FileSearch(ctx context.Context, in *SearchFileInfo, opts ...grpc.CallOption) (*FoundFile, error) {
	out := new(FoundFile)
	err := c.cc.Invoke(ctx, "/styxevent.Styx/FileSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *styxClient) FileSearchStream(ctx context.Context, opts ...grpc.CallOption) (Styx_FileSearchStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Styx_serviceDesc.Streams[0], "/styxevent.Styx/FileSearchStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &styxFileSearchStreamClient{stream}
	return x, nil
}

type Styx_FileSearchStreamClient interface {
	Send(*SearchFileInfo) error
	Recv() (*FoundFile, error)
	grpc.ClientStream
}

type styxFileSearchStreamClient struct {
	grpc.ClientStream
}

func (x *styxFileSearchStreamClient) Send(m *SearchFileInfo) error {
	return x.ClientStream.SendMsg(m)
}

func (x *styxFileSearchStreamClient) Recv() (*FoundFile, error) {
	m := new(FoundFile)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *styxClient) ReqFileTransfer(ctx context.Context, in *RequestFileTransfer, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/styxevent.Styx/ReqFileTransfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *styxClient) PullFile(ctx context.Context, in *GetRemoteFile, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/styxevent.Styx/PullFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StyxServer is the server API for Styx service.
type StyxServer interface {
	FileSearch(context.Context, *SearchFileInfo) (*FoundFile, error)
	FileSearchStream(Styx_FileSearchStreamServer) error
	ReqFileTransfer(context.Context, *RequestFileTransfer) (*Ack, error)
	PullFile(context.Context, *GetRemoteFile) (*Ack, error)
}

func RegisterStyxServer(s *grpc.Server, srv StyxServer) {
	s.RegisterService(&_Styx_serviceDesc, srv)
}

func _Styx_FileSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchFileInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StyxServer).FileSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/styxevent.Styx/FileSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StyxServer).FileSearch(ctx, req.(*SearchFileInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Styx_FileSearchStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StyxServer).FileSearchStream(&styxFileSearchStreamServer{stream})
}

type Styx_FileSearchStreamServer interface {
	Send(*FoundFile) error
	Recv() (*SearchFileInfo, error)
	grpc.ServerStream
}

type styxFileSearchStreamServer struct {
	grpc.ServerStream
}

func (x *styxFileSearchStreamServer) Send(m *FoundFile) error {
	return x.ServerStream.SendMsg(m)
}

func (x *styxFileSearchStreamServer) Recv() (*SearchFileInfo, error) {
	m := new(SearchFileInfo)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Styx_ReqFileTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestFileTransfer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StyxServer).ReqFileTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/styxevent.Styx/ReqFileTransfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StyxServer).ReqFileTransfer(ctx, req.(*RequestFileTransfer))
	}
	return interceptor(ctx, in, info, handler)
}

func _Styx_PullFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRemoteFile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StyxServer).PullFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/styxevent.Styx/PullFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StyxServer).PullFile(ctx, req.(*GetRemoteFile))
	}
	return interceptor(ctx, in, info, handler)
}

var _Styx_serviceDesc = grpc.ServiceDesc{
	ServiceName: "styxevent.Styx",
	HandlerType: (*StyxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FileSearch",
			Handler:    _Styx_FileSearch_Handler,
		},
		{
			MethodName: "ReqFileTransfer",
			Handler:    _Styx_ReqFileTransfer_Handler,
		},
		{
			MethodName: "PullFile",
			Handler:    _Styx_PullFile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FileSearchStream",
			Handler:       _Styx_FileSearchStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "styxevent.proto",
}
