// Code generated by protoc-gen-go. DO NOT EDIT.
// source: styxevent.proto

package styxevent

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Ack struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ack) Reset()         { *m = Ack{} }
func (m *Ack) String() string { return proto.CompactTextString(m) }
func (*Ack) ProtoMessage()    {}
func (*Ack) Descriptor() ([]byte, []int) {
	return fileDescriptor_styxevent_791364d58c4f47a5, []int{0}
}
func (m *Ack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ack.Unmarshal(m, b)
}
func (m *Ack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ack.Marshal(b, m, deterministic)
}
func (dst *Ack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ack.Merge(dst, src)
}
func (m *Ack) XXX_Size() int {
	return xxx_messageInfo_Ack.Size(m)
}
func (m *Ack) XXX_DiscardUnknown() {
	xxx_messageInfo_Ack.DiscardUnknown(m)
}

var xxx_messageInfo_Ack proto.InternalMessageInfo

func (m *Ack) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SearchFileInfo struct {
	Jid                  string   `protobuf:"bytes,1,opt,name=jid,proto3" json:"jid,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Filename             string   `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	Directory            string   `protobuf:"bytes,4,opt,name=directory,proto3" json:"directory,omitempty"`
	Server               string   `protobuf:"bytes,5,opt,name=server,proto3" json:"server,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchFileInfo) Reset()         { *m = SearchFileInfo{} }
func (m *SearchFileInfo) String() string { return proto.CompactTextString(m) }
func (*SearchFileInfo) ProtoMessage()    {}
func (*SearchFileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_styxevent_791364d58c4f47a5, []int{1}
}
func (m *SearchFileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchFileInfo.Unmarshal(m, b)
}
func (m *SearchFileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchFileInfo.Marshal(b, m, deterministic)
}
func (dst *SearchFileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchFileInfo.Merge(dst, src)
}
func (m *SearchFileInfo) XXX_Size() int {
	return xxx_messageInfo_SearchFileInfo.Size(m)
}
func (m *SearchFileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchFileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SearchFileInfo proto.InternalMessageInfo

func (m *SearchFileInfo) GetJid() string {
	if m != nil {
		return m.Jid
	}
	return ""
}

func (m *SearchFileInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SearchFileInfo) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *SearchFileInfo) GetDirectory() string {
	if m != nil {
		return m.Directory
	}
	return ""
}

func (m *SearchFileInfo) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

type FoundFile struct {
	Jid                  string   `protobuf:"bytes,1,opt,name=jid,proto3" json:"jid,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Match                string   `protobuf:"bytes,3,opt,name=match,proto3" json:"match,omitempty"`
	Regmatch             string   `protobuf:"bytes,4,opt,name=regmatch,proto3" json:"regmatch,omitempty"`
	Error                string   `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FoundFile) Reset()         { *m = FoundFile{} }
func (m *FoundFile) String() string { return proto.CompactTextString(m) }
func (*FoundFile) ProtoMessage()    {}
func (*FoundFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_styxevent_791364d58c4f47a5, []int{2}
}
func (m *FoundFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FoundFile.Unmarshal(m, b)
}
func (m *FoundFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FoundFile.Marshal(b, m, deterministic)
}
func (dst *FoundFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FoundFile.Merge(dst, src)
}
func (m *FoundFile) XXX_Size() int {
	return xxx_messageInfo_FoundFile.Size(m)
}
func (m *FoundFile) XXX_DiscardUnknown() {
	xxx_messageInfo_FoundFile.DiscardUnknown(m)
}

var xxx_messageInfo_FoundFile proto.InternalMessageInfo

func (m *FoundFile) GetJid() string {
	if m != nil {
		return m.Jid
	}
	return ""
}

func (m *FoundFile) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *FoundFile) GetMatch() string {
	if m != nil {
		return m.Match
	}
	return ""
}

func (m *FoundFile) GetRegmatch() string {
	if m != nil {
		return m.Regmatch
	}
	return ""
}

func (m *FoundFile) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Ack)(nil), "styxevent.Ack")
	proto.RegisterType((*SearchFileInfo)(nil), "styxevent.SearchFileInfo")
	proto.RegisterType((*FoundFile)(nil), "styxevent.FoundFile")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StyxClient is the client API for Styx service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StyxClient interface {
	FileSearch(ctx context.Context, in *SearchFileInfo, opts ...grpc.CallOption) (*FoundFile, error)
	FileSearchStream(ctx context.Context, opts ...grpc.CallOption) (Styx_FileSearchStreamClient, error)
}

type styxClient struct {
	cc *grpc.ClientConn
}

func NewStyxClient(cc *grpc.ClientConn) StyxClient {
	return &styxClient{cc}
}

func (c *styxClient) FileSearch(ctx context.Context, in *SearchFileInfo, opts ...grpc.CallOption) (*FoundFile, error) {
	out := new(FoundFile)
	err := c.cc.Invoke(ctx, "/styxevent.Styx/FileSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *styxClient) FileSearchStream(ctx context.Context, opts ...grpc.CallOption) (Styx_FileSearchStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Styx_serviceDesc.Streams[0], "/styxevent.Styx/FileSearchStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &styxFileSearchStreamClient{stream}
	return x, nil
}

type Styx_FileSearchStreamClient interface {
	Send(*SearchFileInfo) error
	Recv() (*FoundFile, error)
	grpc.ClientStream
}

type styxFileSearchStreamClient struct {
	grpc.ClientStream
}

func (x *styxFileSearchStreamClient) Send(m *SearchFileInfo) error {
	return x.ClientStream.SendMsg(m)
}

func (x *styxFileSearchStreamClient) Recv() (*FoundFile, error) {
	m := new(FoundFile)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StyxServer is the server API for Styx service.
type StyxServer interface {
	FileSearch(context.Context, *SearchFileInfo) (*FoundFile, error)
	FileSearchStream(Styx_FileSearchStreamServer) error
}

func RegisterStyxServer(s *grpc.Server, srv StyxServer) {
	s.RegisterService(&_Styx_serviceDesc, srv)
}

func _Styx_FileSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchFileInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StyxServer).FileSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/styxevent.Styx/FileSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StyxServer).FileSearch(ctx, req.(*SearchFileInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Styx_FileSearchStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StyxServer).FileSearchStream(&styxFileSearchStreamServer{stream})
}

type Styx_FileSearchStreamServer interface {
	Send(*FoundFile) error
	Recv() (*SearchFileInfo, error)
	grpc.ServerStream
}

type styxFileSearchStreamServer struct {
	grpc.ServerStream
}

func (x *styxFileSearchStreamServer) Send(m *FoundFile) error {
	return x.ServerStream.SendMsg(m)
}

func (x *styxFileSearchStreamServer) Recv() (*SearchFileInfo, error) {
	m := new(SearchFileInfo)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Styx_serviceDesc = grpc.ServiceDesc{
	ServiceName: "styxevent.Styx",
	HandlerType: (*StyxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FileSearch",
			Handler:    _Styx_FileSearch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FileSearchStream",
			Handler:       _Styx_FileSearchStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "styxevent.proto",
}

func init() { proto.RegisterFile("styxevent.proto", fileDescriptor_styxevent_791364d58c4f47a5) }

var fileDescriptor_styxevent_791364d58c4f47a5 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xc1, 0x4e, 0xbb, 0x40,
	0x10, 0xc6, 0xb3, 0x7f, 0x68, 0xff, 0x32, 0x07, 0x6d, 0x36, 0x8d, 0x59, 0x89, 0x89, 0x86, 0x53,
	0xbd, 0x10, 0xa3, 0x67, 0x0f, 0xf6, 0x50, 0xe3, 0xcd, 0xc8, 0x13, 0xac, 0x30, 0xa5, 0x28, 0xb0,
	0x64, 0x58, 0x1b, 0x78, 0x03, 0x4f, 0x3e, 0xb3, 0x61, 0x97, 0xb2, 0x7a, 0xd3, 0xdb, 0xfe, 0xbe,
	0x6f, 0x66, 0xe7, 0xcb, 0x0c, 0x9c, 0xb4, 0xba, 0xef, 0x70, 0x8f, 0xb5, 0x8e, 0x1b, 0x52, 0x5a,
	0xf1, 0x60, 0x12, 0xa2, 0x0b, 0xf0, 0xee, 0xd3, 0x37, 0x2e, 0xe0, 0x7f, 0x85, 0x6d, 0x2b, 0x73,
	0x14, 0xec, 0x92, 0xad, 0x82, 0xe7, 0x03, 0x46, 0x1f, 0x0c, 0x8e, 0x13, 0x94, 0x94, 0xee, 0x36,
	0x45, 0x89, 0x8f, 0xf5, 0x56, 0xf1, 0x05, 0x78, 0xaf, 0x45, 0x36, 0x16, 0x0e, 0x4f, 0xce, 0xc1,
	0xd7, 0x7d, 0x83, 0xe2, 0x9f, 0x91, 0xcc, 0x9b, 0x87, 0x70, 0xb4, 0x2d, 0x4a, 0xac, 0x65, 0x85,
	0xc2, 0x33, 0xfa, 0xc4, 0xfc, 0x1c, 0x82, 0xac, 0x20, 0x4c, 0xb5, 0xa2, 0x5e, 0xf8, 0xc6, 0x74,
	0x02, 0x3f, 0x85, 0x79, 0x8b, 0xb4, 0x47, 0x12, 0x33, 0x63, 0x8d, 0x14, 0xf5, 0x10, 0x6c, 0xd4,
	0x7b, 0x9d, 0x0d, 0x41, 0x7e, 0x19, 0x62, 0x09, 0xb3, 0x4a, 0xea, 0x74, 0x37, 0x26, 0xb0, 0x30,
	0x44, 0x23, 0xcc, 0xad, 0x61, 0xa7, 0x4f, 0x3c, 0x74, 0x20, 0x91, 0x3a, 0xcc, 0xb6, 0x70, 0xf3,
	0xc9, 0xc0, 0x4f, 0x74, 0xdf, 0xf1, 0x3b, 0x80, 0x61, 0xbc, 0xdd, 0x08, 0x3f, 0x8b, 0xdd, 0x6a,
	0x7f, 0x2e, 0x29, 0x5c, 0x7e, 0xb3, 0x5c, 0xea, 0x07, 0x58, 0xb8, 0xf6, 0x44, 0x13, 0xca, 0xea,
	0xcf, 0x9f, 0xac, 0xd8, 0x35, 0x5b, 0x5f, 0x41, 0x58, 0xa8, 0x38, 0xa7, 0x26, 0x8d, 0xb1, 0x93,
	0x55, 0x53, 0x62, 0xeb, 0x6a, 0xd7, 0xee, 0xc0, 0x4f, 0xec, 0x65, 0x6e, 0x8e, 0x7e, 0xfb, 0x15,
	0x00, 0x00, 0xff, 0xff, 0xac, 0x66, 0x96, 0x87, 0x07, 0x02, 0x00, 0x00,
}
