host_config:
  node_id: localhost
  node_type: dmz
  ip_address: 127.0.0.1
  grpc_port: 28888
  sftp_port: 28889
  sz: dmz
  sftp_auth:
    hostkey_file: configs/ssh_host_rsa_key #need to fix this field
  external_access: false
master_config:
  master_ip: 127.0.0.1
  master_port: 28888