host_config:
  node_id: docker-styx3
  node_type: master
  ip_address: 192.168.28.13
  grpc_port: 28888
  sftp_port: 28889
  sz: data
  grpc_auth:
    tls_cert_file: styxnode.pem
    tls_key_file: styxnode-key.pem
    token: "12345"
  sftp_auth:
    hostkey_file: host_key #need to fix this field
  external_access: false
  master_config:
    master_ip: 192.168.28.13
    master_port: 28888
