host_config:
  node_id: docker-styx1
  node_type: node
  ip_address: 192.168.28.11
  grpc_port: 28888
  sftp_port: 28889
  sz: dmz
  grpc_auth:
    tls_cert_file: styxnode.pem
    tls_key_file: styxnode-key.pem
    token: "12345"
  sftp_auth:
    hostkey_file: host_key #need to fix this field
  external_access: false
master_config:
  master_ip: 192.168.28.13
  grpc_port: 28888