// Code generated by protoc-gen-go. DO NOT EDIT.
// source: filetransfer_events.proto

package filetransfer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Condition_ConditionType int32

const (
	Condition_CONDITION_TYPE_UNSPECIFIED Condition_ConditionType = 0
	Condition_TIME                       Condition_ConditionType = 1
	Condition_TIME_RANGE                 Condition_ConditionType = 2
	Condition_REGEX                      Condition_ConditionType = 3
	Condition_GLOB                       Condition_ConditionType = 4
)

var Condition_ConditionType_name = map[int32]string{
	0: "CONDITION_TYPE_UNSPECIFIED",
	1: "TIME",
	2: "TIME_RANGE",
	3: "REGEX",
	4: "GLOB",
}

var Condition_ConditionType_value = map[string]int32{
	"CONDITION_TYPE_UNSPECIFIED": 0,
	"TIME":                       1,
	"TIME_RANGE":                 2,
	"REGEX":                      3,
	"GLOB":                       4,
}

func (x Condition_ConditionType) String() string {
	return proto.EnumName(Condition_ConditionType_name, int32(x))
}

func (Condition_ConditionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4de00028a424494b, []int{3, 0}
}

type RemoteDirectoryTransfer_TransferType int32

const (
	RemoteDirectoryTransfer_TRANSFER_TYPE_UNSPECIFIED RemoteDirectoryTransfer_TransferType = 0
	RemoteDirectoryTransfer_PULL                      RemoteDirectoryTransfer_TransferType = 1
	RemoteDirectoryTransfer_PUSH                      RemoteDirectoryTransfer_TransferType = 2
)

var RemoteDirectoryTransfer_TransferType_name = map[int32]string{
	0: "TRANSFER_TYPE_UNSPECIFIED",
	1: "PULL",
	2: "PUSH",
}

var RemoteDirectoryTransfer_TransferType_value = map[string]int32{
	"TRANSFER_TYPE_UNSPECIFIED": 0,
	"PULL":                      1,
	"PUSH":                      2,
}

func (x RemoteDirectoryTransfer_TransferType) String() string {
	return proto.EnumName(RemoteDirectoryTransfer_TransferType_name, int32(x))
}

func (RemoteDirectoryTransfer_TransferType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4de00028a424494b, []int{5, 0}
}

// filelistevents:
type RemoteDirectory struct {
	SourcePath           string   `protobuf:"bytes,1,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoteDirectory) Reset()         { *m = RemoteDirectory{} }
func (m *RemoteDirectory) String() string { return proto.CompactTextString(m) }
func (*RemoteDirectory) ProtoMessage()    {}
func (*RemoteDirectory) Descriptor() ([]byte, []int) {
	return fileDescriptor_4de00028a424494b, []int{0}
}

func (m *RemoteDirectory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteDirectory.Unmarshal(m, b)
}
func (m *RemoteDirectory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteDirectory.Marshal(b, m, deterministic)
}
func (m *RemoteDirectory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteDirectory.Merge(m, src)
}
func (m *RemoteDirectory) XXX_Size() int {
	return xxx_messageInfo_RemoteDirectory.Size(m)
}
func (m *RemoteDirectory) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteDirectory.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteDirectory proto.InternalMessageInfo

func (m *RemoteDirectory) GetSourcePath() string {
	if m != nil {
		return m.SourcePath
	}
	return ""
}

type RemoteFile struct {
	Sourcefile           string   `protobuf:"bytes,1,opt,name=sourcefile,proto3" json:"sourcefile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoteFile) Reset()         { *m = RemoteFile{} }
func (m *RemoteFile) String() string { return proto.CompactTextString(m) }
func (*RemoteFile) ProtoMessage()    {}
func (*RemoteFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_4de00028a424494b, []int{1}
}

func (m *RemoteFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteFile.Unmarshal(m, b)
}
func (m *RemoteFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteFile.Marshal(b, m, deterministic)
}
func (m *RemoteFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteFile.Merge(m, src)
}
func (m *RemoteFile) XXX_Size() int {
	return xxx_messageInfo_RemoteFile.Size(m)
}
func (m *RemoteFile) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteFile.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteFile proto.InternalMessageInfo

func (m *RemoteFile) GetSourcefile() string {
	if m != nil {
		return m.Sourcefile
	}
	return ""
}

type TimeValues struct {
	TimeStart            int64    `protobuf:"varint,1,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
	TimeEnd              int64    `protobuf:"varint,2,opt,name=time_end,json=timeEnd,proto3" json:"time_end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeValues) Reset()         { *m = TimeValues{} }
func (m *TimeValues) String() string { return proto.CompactTextString(m) }
func (*TimeValues) ProtoMessage()    {}
func (*TimeValues) Descriptor() ([]byte, []int) {
	return fileDescriptor_4de00028a424494b, []int{2}
}

func (m *TimeValues) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeValues.Unmarshal(m, b)
}
func (m *TimeValues) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeValues.Marshal(b, m, deterministic)
}
func (m *TimeValues) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeValues.Merge(m, src)
}
func (m *TimeValues) XXX_Size() int {
	return xxx_messageInfo_TimeValues.Size(m)
}
func (m *TimeValues) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeValues.DiscardUnknown(m)
}

var xxx_messageInfo_TimeValues proto.InternalMessageInfo

func (m *TimeValues) GetTimeStart() int64 {
	if m != nil {
		return m.TimeStart
	}
	return 0
}

func (m *TimeValues) GetTimeEnd() int64 {
	if m != nil {
		return m.TimeEnd
	}
	return 0
}

type Condition struct {
	ConditionType Condition_ConditionType `protobuf:"varint,1,opt,name=condition_type,json=conditionType,proto3,enum=filetransfer.Condition_ConditionType" json:"condition_type,omitempty"`
	// Types that are valid to be assigned to ConditionValue:
	//	*Condition_TimeValues
	//	*Condition_Pattern
	ConditionValue       isCondition_ConditionValue `protobuf_oneof:"condition_value"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Condition) Reset()         { *m = Condition{} }
func (m *Condition) String() string { return proto.CompactTextString(m) }
func (*Condition) ProtoMessage()    {}
func (*Condition) Descriptor() ([]byte, []int) {
	return fileDescriptor_4de00028a424494b, []int{3}
}

func (m *Condition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Condition.Unmarshal(m, b)
}
func (m *Condition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Condition.Marshal(b, m, deterministic)
}
func (m *Condition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Condition.Merge(m, src)
}
func (m *Condition) XXX_Size() int {
	return xxx_messageInfo_Condition.Size(m)
}
func (m *Condition) XXX_DiscardUnknown() {
	xxx_messageInfo_Condition.DiscardUnknown(m)
}

var xxx_messageInfo_Condition proto.InternalMessageInfo

func (m *Condition) GetConditionType() Condition_ConditionType {
	if m != nil {
		return m.ConditionType
	}
	return Condition_CONDITION_TYPE_UNSPECIFIED
}

type isCondition_ConditionValue interface {
	isCondition_ConditionValue()
}

type Condition_TimeValues struct {
	TimeValues *TimeValues `protobuf:"bytes,2,opt,name=time_values,json=timeValues,proto3,oneof"`
}

type Condition_Pattern struct {
	Pattern string `protobuf:"bytes,3,opt,name=pattern,proto3,oneof"`
}

func (*Condition_TimeValues) isCondition_ConditionValue() {}

func (*Condition_Pattern) isCondition_ConditionValue() {}

func (m *Condition) GetConditionValue() isCondition_ConditionValue {
	if m != nil {
		return m.ConditionValue
	}
	return nil
}

func (m *Condition) GetTimeValues() *TimeValues {
	if x, ok := m.GetConditionValue().(*Condition_TimeValues); ok {
		return x.TimeValues
	}
	return nil
}

func (m *Condition) GetPattern() string {
	if x, ok := m.GetConditionValue().(*Condition_Pattern); ok {
		return x.Pattern
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Condition) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Condition_TimeValues)(nil),
		(*Condition_Pattern)(nil),
	}
}

type RemoteDirectoryCondition struct {
	SourcePath           string       `protobuf:"bytes,1,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	Condition            []*Condition `protobuf:"bytes,2,rep,name=condition,proto3" json:"condition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RemoteDirectoryCondition) Reset()         { *m = RemoteDirectoryCondition{} }
func (m *RemoteDirectoryCondition) String() string { return proto.CompactTextString(m) }
func (*RemoteDirectoryCondition) ProtoMessage()    {}
func (*RemoteDirectoryCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_4de00028a424494b, []int{4}
}

func (m *RemoteDirectoryCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteDirectoryCondition.Unmarshal(m, b)
}
func (m *RemoteDirectoryCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteDirectoryCondition.Marshal(b, m, deterministic)
}
func (m *RemoteDirectoryCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteDirectoryCondition.Merge(m, src)
}
func (m *RemoteDirectoryCondition) XXX_Size() int {
	return xxx_messageInfo_RemoteDirectoryCondition.Size(m)
}
func (m *RemoteDirectoryCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteDirectoryCondition.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteDirectoryCondition proto.InternalMessageInfo

func (m *RemoteDirectoryCondition) GetSourcePath() string {
	if m != nil {
		return m.SourcePath
	}
	return ""
}

func (m *RemoteDirectoryCondition) GetCondition() []*Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

// filetransferevents
type RemoteDirectoryTransfer struct {
	TransferType         RemoteDirectoryTransfer_TransferType `protobuf:"varint,1,opt,name=transfer_type,json=transferType,proto3,enum=filetransfer.RemoteDirectoryTransfer_TransferType" json:"transfer_type,omitempty"`
	SourcePath           string                               `protobuf:"bytes,2,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	DestinationPath      string                               `protobuf:"bytes,3,opt,name=destination_path,json=destinationPath,proto3" json:"destination_path,omitempty"`
	RemoteServer         string                               `protobuf:"bytes,4,opt,name=remote_server,json=remoteServer,proto3" json:"remote_server,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *RemoteDirectoryTransfer) Reset()         { *m = RemoteDirectoryTransfer{} }
func (m *RemoteDirectoryTransfer) String() string { return proto.CompactTextString(m) }
func (*RemoteDirectoryTransfer) ProtoMessage()    {}
func (*RemoteDirectoryTransfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_4de00028a424494b, []int{5}
}

func (m *RemoteDirectoryTransfer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteDirectoryTransfer.Unmarshal(m, b)
}
func (m *RemoteDirectoryTransfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteDirectoryTransfer.Marshal(b, m, deterministic)
}
func (m *RemoteDirectoryTransfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteDirectoryTransfer.Merge(m, src)
}
func (m *RemoteDirectoryTransfer) XXX_Size() int {
	return xxx_messageInfo_RemoteDirectoryTransfer.Size(m)
}
func (m *RemoteDirectoryTransfer) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteDirectoryTransfer.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteDirectoryTransfer proto.InternalMessageInfo

func (m *RemoteDirectoryTransfer) GetTransferType() RemoteDirectoryTransfer_TransferType {
	if m != nil {
		return m.TransferType
	}
	return RemoteDirectoryTransfer_TRANSFER_TYPE_UNSPECIFIED
}

func (m *RemoteDirectoryTransfer) GetSourcePath() string {
	if m != nil {
		return m.SourcePath
	}
	return ""
}

func (m *RemoteDirectoryTransfer) GetDestinationPath() string {
	if m != nil {
		return m.DestinationPath
	}
	return ""
}

func (m *RemoteDirectoryTransfer) GetRemoteServer() string {
	if m != nil {
		return m.RemoteServer
	}
	return ""
}

type RemoteDirectoryConditionTransfer struct {
	RemoteDirectory      *RemoteDirectoryTransfer `protobuf:"bytes,1,opt,name=remote_directory,json=remoteDirectory,proto3" json:"remote_directory,omitempty"`
	Precondition         *Condition               `protobuf:"bytes,2,opt,name=precondition,proto3" json:"precondition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *RemoteDirectoryConditionTransfer) Reset()         { *m = RemoteDirectoryConditionTransfer{} }
func (m *RemoteDirectoryConditionTransfer) String() string { return proto.CompactTextString(m) }
func (*RemoteDirectoryConditionTransfer) ProtoMessage()    {}
func (*RemoteDirectoryConditionTransfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_4de00028a424494b, []int{6}
}

func (m *RemoteDirectoryConditionTransfer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteDirectoryConditionTransfer.Unmarshal(m, b)
}
func (m *RemoteDirectoryConditionTransfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteDirectoryConditionTransfer.Marshal(b, m, deterministic)
}
func (m *RemoteDirectoryConditionTransfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteDirectoryConditionTransfer.Merge(m, src)
}
func (m *RemoteDirectoryConditionTransfer) XXX_Size() int {
	return xxx_messageInfo_RemoteDirectoryConditionTransfer.Size(m)
}
func (m *RemoteDirectoryConditionTransfer) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteDirectoryConditionTransfer.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteDirectoryConditionTransfer proto.InternalMessageInfo

func (m *RemoteDirectoryConditionTransfer) GetRemoteDirectory() *RemoteDirectoryTransfer {
	if m != nil {
		return m.RemoteDirectory
	}
	return nil
}

func (m *RemoteDirectoryConditionTransfer) GetPrecondition() *Condition {
	if m != nil {
		return m.Precondition
	}
	return nil
}

type TransferStatus struct {
	TransferredFile      string   `protobuf:"bytes,1,opt,name=transferred_file,json=transferredFile,proto3" json:"transferred_file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferStatus) Reset()         { *m = TransferStatus{} }
func (m *TransferStatus) String() string { return proto.CompactTextString(m) }
func (*TransferStatus) ProtoMessage()    {}
func (*TransferStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_4de00028a424494b, []int{7}
}

func (m *TransferStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferStatus.Unmarshal(m, b)
}
func (m *TransferStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferStatus.Marshal(b, m, deterministic)
}
func (m *TransferStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferStatus.Merge(m, src)
}
func (m *TransferStatus) XXX_Size() int {
	return xxx_messageInfo_TransferStatus.Size(m)
}
func (m *TransferStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferStatus.DiscardUnknown(m)
}

var xxx_messageInfo_TransferStatus proto.InternalMessageInfo

func (m *TransferStatus) GetTransferredFile() string {
	if m != nil {
		return m.TransferredFile
	}
	return ""
}

func init() {
	proto.RegisterEnum("filetransfer.Condition_ConditionType", Condition_ConditionType_name, Condition_ConditionType_value)
	proto.RegisterEnum("filetransfer.RemoteDirectoryTransfer_TransferType", RemoteDirectoryTransfer_TransferType_name, RemoteDirectoryTransfer_TransferType_value)
	proto.RegisterType((*RemoteDirectory)(nil), "filetransfer.RemoteDirectory")
	proto.RegisterType((*RemoteFile)(nil), "filetransfer.RemoteFile")
	proto.RegisterType((*TimeValues)(nil), "filetransfer.TimeValues")
	proto.RegisterType((*Condition)(nil), "filetransfer.Condition")
	proto.RegisterType((*RemoteDirectoryCondition)(nil), "filetransfer.RemoteDirectoryCondition")
	proto.RegisterType((*RemoteDirectoryTransfer)(nil), "filetransfer.RemoteDirectoryTransfer")
	proto.RegisterType((*RemoteDirectoryConditionTransfer)(nil), "filetransfer.RemoteDirectoryConditionTransfer")
	proto.RegisterType((*TransferStatus)(nil), "filetransfer.TransferStatus")
}

func init() { proto.RegisterFile("filetransfer_events.proto", fileDescriptor_4de00028a424494b) }

var fileDescriptor_4de00028a424494b = []byte{
	// 552 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x4b, 0x6f, 0xda, 0x4c,
	0x14, 0xc5, 0x86, 0xef, 0x4b, 0xb8, 0xbc, 0xdc, 0xd9, 0xc4, 0x44, 0x4a, 0x8a, 0x5c, 0x55, 0x4a,
	0xa5, 0x8a, 0x05, 0x55, 0x57, 0xac, 0x78, 0x98, 0x87, 0x44, 0x01, 0x8d, 0x9d, 0xbe, 0x16, 0xb5,
	0x5c, 0x7c, 0xa3, 0x58, 0x02, 0xdb, 0x1a, 0x0f, 0x48, 0xfc, 0xa0, 0x76, 0xdf, 0x7f, 0x58, 0xcd,
	0x80, 0x61, 0xa0, 0xa2, 0xdd, 0xcd, 0x9c, 0x7b, 0xee, 0xeb, 0x1c, 0x7b, 0xa0, 0xfe, 0x14, 0x2e,
	0x91, 0x33, 0x3f, 0x4a, 0x9f, 0x90, 0x79, 0xb8, 0xc1, 0x88, 0xa7, 0xcd, 0x84, 0xc5, 0x3c, 0x26,
	0x65, 0x35, 0x64, 0xb5, 0xa0, 0x46, 0x71, 0x15, 0x73, 0xec, 0x87, 0x0c, 0x17, 0x3c, 0x66, 0x5b,
	0xf2, 0x12, 0x4a, 0x69, 0xbc, 0x66, 0x0b, 0xf4, 0x12, 0x9f, 0x3f, 0x9b, 0x5a, 0x43, 0x7b, 0x28,
	0x52, 0xd8, 0x41, 0x73, 0x9f, 0x3f, 0x5b, 0x6f, 0x01, 0x76, 0x39, 0x83, 0x70, 0x89, 0xe4, 0x1e,
	0xf6, 0x31, 0x51, 0xf7, 0x94, 0x2d, 0x10, 0x6b, 0x00, 0xe0, 0x86, 0x2b, 0xfc, 0xe8, 0x2f, 0xd7,
	0x98, 0x92, 0x3b, 0x00, 0x1e, 0xae, 0xd0, 0x4b, 0xb9, 0xcf, 0xb8, 0x64, 0xe7, 0x69, 0x51, 0x20,
	0x8e, 0x00, 0x48, 0x1d, 0xae, 0x65, 0x18, 0xa3, 0xc0, 0xd4, 0x65, 0xf0, 0x4a, 0xdc, 0xed, 0x28,
	0xb0, 0x7e, 0xe8, 0x50, 0xec, 0xc5, 0x51, 0x10, 0xf2, 0x30, 0x8e, 0xc8, 0x04, 0xaa, 0x8b, 0xec,
	0xe2, 0xf1, 0x6d, 0xb2, 0xeb, 0x5c, 0x6d, 0xbd, 0x6e, 0xaa, 0xeb, 0x35, 0x0f, 0x09, 0xc7, 0x93,
	0xbb, 0x4d, 0x90, 0x56, 0x16, 0xea, 0x95, 0xb4, 0xa1, 0x24, 0xdb, 0x6e, 0xe4, 0x90, 0xb2, 0x73,
	0xa9, 0x65, 0x9e, 0x96, 0x3a, 0x2e, 0x31, 0xca, 0x51, 0xb9, 0xc4, 0x7e, 0xa5, 0x5b, 0xb8, 0x4a,
	0x7c, 0xce, 0x91, 0x45, 0x66, 0x5e, 0x6c, 0x3f, 0xca, 0xd1, 0x0c, 0xb0, 0xbe, 0x41, 0xe5, 0xa4,
	0x31, 0xb9, 0x87, 0xdb, 0xde, 0x6c, 0xda, 0x1f, 0xbb, 0xe3, 0xd9, 0xd4, 0x73, 0xbf, 0xcc, 0x6d,
	0xef, 0x71, 0xea, 0xcc, 0xed, 0xde, 0x78, 0x30, 0xb6, 0xfb, 0x46, 0x8e, 0x5c, 0x43, 0xc1, 0x1d,
	0x7f, 0xb0, 0x0d, 0x8d, 0x54, 0x01, 0xc4, 0xc9, 0xa3, 0x9d, 0xe9, 0xd0, 0x36, 0x74, 0x52, 0x84,
	0xff, 0xa8, 0x3d, 0xb4, 0x3f, 0x1b, 0x79, 0x41, 0x1a, 0x4e, 0x66, 0x5d, 0xa3, 0xd0, 0x7d, 0x01,
	0xb5, 0xa3, 0x0c, 0x72, 0x7a, 0x8b, 0x81, 0x79, 0xe6, 0xe8, 0x51, 0xb5, 0x7f, 0x59, 0x4b, 0xde,
	0x43, 0xf1, 0x50, 0xcf, 0xd4, 0x1b, 0xf9, 0x87, 0x52, 0xeb, 0xe6, 0x82, 0xa2, 0xf4, 0xc8, 0xb4,
	0x7e, 0xea, 0x70, 0x73, 0xd6, 0xd4, 0xdd, 0x27, 0x90, 0x4f, 0x50, 0x39, 0x7c, 0x88, 0x8a, 0x51,
	0xad, 0xd3, 0xb2, 0x17, 0xb2, 0x9b, 0xd9, 0x41, 0xba, 0x56, 0xe6, 0xca, 0xed, 0x7c, 0x19, 0xfd,
	0x8f, 0x65, 0xde, 0x80, 0x11, 0x60, 0xca, 0xc3, 0xc8, 0x97, 0xf2, 0x48, 0x96, 0x74, 0x88, 0xd6,
	0x14, 0x5c, 0x52, 0x5f, 0x41, 0x85, 0xc9, 0x09, 0xbc, 0x14, 0xd9, 0x06, 0x99, 0x59, 0x90, 0xbc,
	0xf2, 0x0e, 0x74, 0x24, 0x66, 0x75, 0xa0, 0xac, 0x8e, 0x43, 0xee, 0xa0, 0xee, 0xd2, 0xce, 0xd4,
	0x19, 0xd8, 0xf4, 0x82, 0x95, 0xf3, 0xc7, 0xc9, 0xc4, 0xd0, 0x76, 0x27, 0x67, 0x64, 0xe8, 0xd6,
	0x2f, 0x0d, 0x1a, 0x97, 0xdc, 0x39, 0x28, 0x36, 0x07, 0x63, 0x3f, 0x4c, 0x90, 0x91, 0xa4, 0x68,
	0xa5, 0xf3, 0xaf, 0xfb, 0x82, 0x68, 0xb4, 0xc6, 0xce, 0x7e, 0xe9, 0x36, 0x94, 0x13, 0x86, 0xaa,
	0xb3, 0xda, 0xdf, 0x9c, 0x3d, 0x21, 0x5b, 0x6d, 0xa8, 0x66, 0x95, 0x1d, 0xee, 0xf3, 0x75, 0x2a,
	0x84, 0xcd, 0xb2, 0x18, 0x06, 0x9e, 0xf2, 0xe3, 0xd7, 0x14, 0x5c, 0xbc, 0x0e, 0x5d, 0xe3, 0x6b,
	0xb5, 0xd9, 0x56, 0xdb, 0x7c, 0xff, 0x5f, 0x3e, 0x43, 0xef, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff,
	0x66, 0xcc, 0xee, 0x8a, 0xa3, 0x04, 0x00, 0x00,
}
